### ISSUE TITLE
jobsteal single thread faster than serial

### ISSUE THREAD

**Issue by rphmeier** [willi-kappler/mandel-rust#1]
That number seems suspect -- I think it's because jobsteal busy-waits at the end of scopes until all jobs submitted are completed, so the scope you spawn on the main thread is actually doing work as well. This actually applies to all the examples -- work is being done on N+1 threads. You could probably alleviate this by creating jobsteal thread pools with "num_threads - 1". I don't know how much this problem applies to the other thread pools, however.

(This may be one reason why jobsteal is being outperformed at 24 threads: assuming that 24 is the number of cores on your machine, jobsteal is attempting to balance work between _25_ threads and paying the price for context switches between them, while thread pools like rayon internally will be using 24)

**Comment by willi-kappler** [comment]
Yes, thanks for pointing that out! It makes sense and I'll try "num_threads -1"

**Comment by rphmeier** [comment]
Yeah, I think that might be an odd thing about jobsteal. When you call `make_pool(N)`, it creates N additional threads on top of the main thread which will exist solely for the purpose of working. The main thread will also do work, but it's a little different than the others since it can only perform work when given the opportunity to via calls to synchronize, scope boundaries, and the destructor.

**Comment by willi-kappler** [comment]
I've finished the benchmark and jobsteal now uses `num_threads - 1`. Looks more reasonable now, if you agree I would close the issue.

**Comment by rphmeier** [comment]
Seems fine, although it is also valid to create a `jobsteal` pool with "0" threads. It'll just only do work in the main thread, so I don't think it needs to be special-cased for `num_threads > 1` as in this code:

``` rust
    // Jobsteal uses n + 1 threads (1 main thread + n sub-threads)
    if mandel_config.num_threads > 1 {
        do_run("job_steal", &job_steal, &mandel_config, &mut image, &time_now);
        do_run("job_steal_join", &job_steal_join, &mandel_config, &mut image, &time_now);
    }
```

I think this misunderstanding is a result of my poor explanations above :).
What I meant by the main thread is the thread which creates the pool. Scopes need to be waited on such that all jobs submitted within them are executed before returning execution to the scope creator. The waiting thread will run jobs in a loop to reduce the time waited. So when you write code like this:

``` rust
let mut pool = make_pool(1);
pool.scope(|scope| { ... });
```

The pool only spawns one additional thread, but both that thread and the main thread will do work while the main thread waits for the scope to finish. 

If you call `make_pool(24)`, it will only spawn 24 threads, but the main thread will also do work when waiting for scopes to conclude or in the pool's destructor. This leads to work being run on 25 threads (the 24 we spawned and the thread that owns the pool) which is more cores than the server has. In practice, I haven't seen this to affect performance very much.

**Comment by willi-kappler** [comment]
Thank you for your detailed explanation!

In Rayon for ex. a pool of zero threads is not allowed, thus I was adding the `if` block for `jobsteal`.
I'll remove the special-case in the next release and add a comment to the code that points it out.
(And probably a link to this issue)
Thanks again :-)
